version: '3.6'

networks:
  network1:

services:

  nginx:
    image: nginx:1.15-alpine
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/steve/mew/MewLabs/eth-dev-kit/config/certs/devCert.cert:/etc/nginx/devCert.cert:ro
      - /home/steve/mew/MewLabs/eth-dev-kit/config/certs/devCert.key:/etc/nginx/devCert.key:ro
    ports:
      # Ethereum Specific
      # JSON RPC
      - 7545:7545 # SSL
      - 8545:8545
      # WebSockets
      - 7546:7546 # SSL
      - 8546:8546

  parity:
    image: parity/parity:v1.11.8
    depends_on:
          - nginx
    volumes:
      - /home/steve/mew/MewLabs/eth-dev-kit/parity/config/:/config
    ports:
      - 8180:8180
      - 30303:30303/udp
    command: >
       --config /config/config.toml

