version: '3.6'

networks:
  web:
    external: true
  back:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24

services:

  geth_miner:
    build:
      context: ./src/eth
      dockerfile: ../../provisioners/docker/images/dev/eth/Dockerfile
    restart: unless-stopped
    volumes:
      - ./provisioners/docker/config/geth/genesis.json:/genesis.json
      - ./provisioners/docker/config/geth/keystore/:/keystore/
    networks:
      back:
        ipv4_address: 172.25.0.101
    command:
      - /bin/zsh
      - -c
      - |
        rm -rf /geth && mkdir -p /geth/keystore
        cp -a /keystore/. /geth/keystore/
        geth --datadir '/geth' init /genesis.json
        geth --datadir '/geth' --networkid 1234 --identity geth_miner --mine --minerthreads 1 --nousb --unlock '84baabad835e6ca9252658cd6eae0152f6330c09' --rpc --rpcaddr '0.0.0.0' --password =(echo '123456789') --nodiscover --maxpeers 2 --nodekeyhex '08f0e1dee5c1b4645f3331a566009e41a4514b6cd28656d63d0449ecf812812b'

  geth:
    build:
      context: ./src/eth
      dockerfile: ../../provisioners/docker/images/dev/eth/Dockerfile
    restart: unless-stopped
    depends_on:
      - geth_miner
      - rethinkdb
    volumes:
      - ./provisioners/docker/config/geth/genesis.json:/genesis.json
      - ./provisioners/docker/config/geth/keystore/:/keystore/
      - ./provisioners/docker/config/geth/static-nodes.json:/static-nodes.json
    networks:
      back:
        ipv4_address: 172.25.0.102
    ports:
      - 8545:8545
    labels:
      - "traefik.enable=true"
      - "traefik.default.protocol=http"
      - "traefik.frontend.rule=Host:geth.ethvm.lan"
      - "traefik.port=9545"
      - "traefik.backend=geth"
    environment:
      - RETHINKDB_URL=http://rethinkdb:28015
    command:
      - /bin/zsh
      - -c
      - |
        rm -rf /geth && mkdir -p /geth/keystore
        cp -a /keystore/. /geth/keystore/
        cp /static-nodes.json /geth/
        geth --datadir '/geth' --ethvm init /genesis.json
        geth --datadir '/geth' --verbosity 6 --networkid 1234 --identity geth --ethvm --gcmode archive --rpc --rpcaddr '0.0.0.0' --rpccorsdomain '*' --rpcapi 'admin,personal,db,eth,net,web3,txpool,miner' --syncmode full --nat 'extip:172.25.0.102' --nousb --nodiscover --maxpeers 2
