version: '3.6'

networks:
  network1:

services:

  nginx:
    image: nginx:1.15-alpine
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/steve/mew/MewLabs/eth-dev-kit/config/certs/devCert.cert:/etc/nginx/devCert.cert:ro
      - /home/steve/mew/MewLabs/eth-dev-kit/config/certs/devCert.key:/etc/nginx/devCert.key:ro
    ports:
      - 7545:7545
    networks:
      - network1

  parity:
    image: parity/parity:v1.11.8
    volumes:
      - /home/steve/mew/MewLabs/eth-dev-kit/parity/config/:/config
    networks:
      - network1
    ports:
      - 8545:8545
      - 8546:8546
      - 8180:8180
      - 30303:30303/udp
    command: >
      --chain /config/parity.json --ui-interface all --jsonrpc-interface all


